server:
  port: 8080
spring:
  # H2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL; # In-Memory mode
    username: sa
    password:
  # JPA
  jpa:
    hibernate:
      ddl-auto: create  # create, create-drop, update, validate, none
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG