spring:
  # H2 DB ?? ??
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:./src/main/resources/data/pes-db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR;AUTO_SERVER=TRUE
    url: jdbc:h2:mem:test;MODE=MySQL; # In-Memory mode
    username: sa
    password:
    hikari:
      maximum-pool-size: 20

  # JPA ?? ??
  jpa:
    hibernate:
      ddl-auto: create  # create, create-drop, update, validate, none
    defer-datasource-initialization: true
    show-sql: true  # true ?? ?, ??? JPA ?? ??
    properties:
      hibernate:
        format_sql: true  # ??? ???? ??? ????? ??
        use_sql_comments: true  # ?? ?? ?, ??? ?? ??

server:
  # ?? ??
  port: 8080
jwt:
  secret-key: "absfdfasdfdsarfaewr23432423sdfsdfqw54235wsadfasdfasf342424234"
  access-token-expiration-millis: 86400000 # 1000 * 60 * 60 * 24 (1?)
  refresh-token-expiration-millis: 604800000 # 1000 * 60 * 60 * 24 * 7 (7?)